# Generated by Django 5.1.1 on 2024-09-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data_da_consulta', models.DateField()),
                ('hora_da_consulta', models.TimeField()),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.especialidade')),
                ('local_da_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.clinicas')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='cadastro.paciente')),
                ('profissional_executante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.profissional')),
            ],
        ),
    ]
