# Generated by Django 5.1.1 on 2024-09-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=50)),
                ('CEP', models.CharField(max_length=9)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_consultorios', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('CNS', models.CharField(max_length=15, unique=True)),
                ('prontuario', models.AutoField(primary_key=True, serialize=False)),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('logradouro', models.CharField(max_length=50)),
                ('CEP', models.CharField(max_length=9)),
                ('numero_casa', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('MED', 'Médico'), ('ENF', 'Enfermeiro'), ('PSI', 'Psicologo'), ('PSQ', 'Psiquiatra'), ('T.O', 'Terapeuta_Ocupacional'), ('FIS', 'Fisioterapeuta'), ('FON', 'Fonoaudiologo'), ('RAD', 'Radiologista'), ('PAT', 'Patologista'), ('BIO', 'BioMedico'), ('NUT', 'Nutricionista'), ('DEN', 'Dentista')], default='MED', max_length=3)),
                ('nome_completo', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('numero_do_registro', models.CharField(max_length=10)),
                ('classe_do_registro', models.CharField(max_length=10)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.especialidade')),
                ('locais_de_trabalho', models.ManyToManyField(to='cadastro.clinicas')),
            ],
        ),
    ]
