# Generated by Django 5.1.1 on 2024-10-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_paciente_numero_casa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='complemento',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
