# Generated by Django 5.1.1 on 2024-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_remove_paciente_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
